parameters:
    pushover:
        baseurl: https://api.pushover.net/1/messages.json
        token: adg3agmc49z6feziyu9ush4597kurc
        user: udufhnuwupk2c2vdxutmoiim6g3gzn
    coinmarketcap:
        baseurl: https://api.coinmarketcap.com/v1/ticker/

